Fixed rvdecodedb
chipsalliance/rvdecoderdb pull request #28
Opened 2024-10-09 17:27 UTC by zlh20040308

Fixed a bug in rvdecoderdb where fields in the format attr1=attr2 were not recognized.

2024-10-09 18:11 UTC, unlsycn requested changes

2024-10-09 18:11 UTC, unlsycn commented on rvdecoderdb/src/parser/parse.scala
> +            .filter(_.trim.nonEmpty)
It may be preferable to map "trim" to each line.

2024-10-09 18:34 UTC, unlsycn requested changes

2024-10-09 18:34 UTC, unlsycn commented on rvdecoderdb/src/parser/SameValue.scala
Please format your code using mill.

2024-10-09 19:02 UTC, zlh20040308 commented on rvdecoderdb/src/parser/SameValue.scala
Thank you for pointing out the issues in my previous PR. I have made the necessary fixes and submitted the updated code. I hope this version meets the requirements. If you have any further feedback or suggestions, please feel free to let me know.

2024-10-10 02:02 UTC, sequencer commented
LGTM! Thanks for contribution!

2024-10-10 02:02 UTC, merged